Repository Emmanuelcik/kanela-devs-front, pull requests merged in 2022-10, with the labels that each got.

#1 [FEATURE] Create file structure
  package-lock.json
  src/App.js
  src/components/Button/index.js
  src/containers/Home/index.js
  src/utils/utils.js
Labels: feature

#2 [SYNC] Develop to master
  package-lock.json
  src/App.js
  src/DB/kdb.json
  src/components/Button/index.js
  src/containers/Home/index.js
  src/utils/utils.js
Labels: sync

#5 Added support to deploy to gh pages
  package-lock.json
  package.json
  src/logo.svg
Labels: infra

#11 Develop
  package-lock.json
  package.json
  src/logo.svg
Labels: sync
